language: 

os:
  - linux
  - osx

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: trusty # Ubuntu 14.04.

compiler:
  - gcc

env:
  - DEBUG=0
  - DEBUG=1

install: sh ./.travis/install-$TRAVIS_OS_NAME-deps.sh

addons:
  apt:
    # Travis whitelist of packages.
    # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    # NOTE(bja, 201604) default gcc is too old.
    packages:
      - cmake


script: 
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC=gcc-5; export CXX=g++-5; export FC=gfortran-5;  else export CC=gcc; export CXX=g++; export FC=gfortran; fi
  - echo CC=${CC}
  - echo CXX=${CXX}
  - echo FC=${FC}
  - make debug=$DEBUG CC=${CC} CXX=${CXX} FC=${FC} config
  - make debug=$DEBUG CC=${CC} CXX=${CXX} FC=${FC} all
  - make debug=$DEBUG CC=${CC} CXX=${CXX} FC=${FC} test
  - make debug=$DEBUG CC=${CC} CXX=${CXX} FC=${FC} install
  - cd regression-tests; make rtest
